### ISSUE TITLE
Checking for updates causes the app to crash

### ISSUE THREAD

**Issue by stasadev** [noisetorch/NoiseTorch#316]
**Describe the bug**
It is impossible to use NoiseTorch without Internet (or if GitHub is down).

**Version**
v0.12.0

**To Reproduce**
Disconnect the Internet and show help for NoiseTorch from the terminal.

```bash
$ noisetorch -h
2022/06/03 19:00:00 Couldn't fetch latest release Get "https://api.github.com/repos/noisetorch/NoiseTorch/releases?per_page=1&page=1": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x556be5779270]

goroutine 1 [running]:
main.getLatestRelease()
        noisetorch/update.go:181 +0x290
main.init()
        noisetorch/update.go:77 +0x2e
```

**Expected behavior**
NoiseTorch should not crash and continue to work as it did before the v0.12.0 release.

**Comment by compico** [comment]
Similar problem. Github can return api rate limit for ip.

GET https://api.github.com/repos/noisetorch/NoiseTorch/releases?per_page=1&page=1
```json
{
    "message" : "API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url" : "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}
```
Noisetorch Error:
```
Reading JSON for latest_release failed json: cannot unmarshal object into Go value of type main.github_releases
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.getLatestRelease()
	noisetorch/update.go:199 +0x477
main.init()
	noisetorch/update.go:77 +0x2e
```

**Comment by stasadev** [comment]
@AXDOOMER Also, you may want to consider that checking for updates is only needed when starting the GUI, not when called from the terminal.
